version: '3.4'

services:
  postgres_service_blablabla:
    image: postgres:18.0
    environment:
      - POSTGRES_DB=dockerdefinitivo
      - POSTGRES_USER=app01
      - POSTGRES_PASSWORD=pass@USER123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - db

  postgres_pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 80:80
    networks:
      - db

volumes:
  postgres_data:
    driver: local

networks:
  db:
    driver: bridge